In [1]:
import pandas as pd

df = pd.read_csv("employees.csv")
df.head()

      Name Department  Salary  Bonus
0    Alice         IT    5200    500
1      Bob         HR    4100    300
2  Charlie         IT    6100    600
3    Diana    Finance    5800    550
4      Eve         IT    4900    450

In [2]:
df.info()
df.describe()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        26 non-null     object
 1   Department  26 non-null     object
 2   Salary      26 non-null     int64
 3   Bonus       26 non-null     int64
dtypes: int64(2), object(2)
memory usage: 964.0+ bytes

Index(['Name', 'Department', 'Salary', 'Bonus'], dtype='object')

In [3]:
df["Name"]
df[["Name", "Salary"]]

       Name  Salary
0     Alice    5200
1       Bob    4100
2   Charlie    6100
3     Diana    5800
4       Eve    4900
5     Frank    4200
6     Grace    6300
7     Heidi    5400
8      Ivan    3900
9      Judy    7200
10    Kevin    5100
11    Laura    4300
12  Mallory    6700
13     Niaj    5600
14   Olivia    4600
15    Peggy    6000
16  Quentin    5800
17   Rupert    4400
18    Sybil    7100
19    Trent    5300
20      Uma    4000
21   Victor    6900
22    Wendy    5700
23   Xavier    4200
24   Yvonne    6500
25     Zara    6000

In [4]:
df[df["Department"] == "IT"]
df[df["Salary"] > 6000]

       Name Department  Salary  Bonus
2   Charlie         IT    6100    600
6     Grace    Finance    6300    700
9      Judy    Finance    7200    800
12  Mallory    Finance    6700    650
18    Sybil    Finance    7100    750
21   Victor    Finance    6900    700
24   Yvonne    Finance    6500    650

In [5]:
df["Total"] = df["Salary"] + df["Bonus"]
df.head()

      Name Department  Salary  Bonus  Total
0    Alice         IT    5200    500   5700
1      Bob         HR    4100    300   4400
2  Charlie         IT    6100    600   6700
3    Diana    Finance    5800    550   6350
4      Eve         IT    4900    450   5350

In [6]:
df.groupby("Department")["Total"].mean()

Department
Finance    7237.50
HR         4506.25
IT         6010.00
Name: Total, dtype: float64

In [7]:
df.groupby("Department").agg({
    "Salary": "mean",
    "Bonus": "sum",
    "Total": "max"
})

            Salary  Bonus  Total
Department
Finance     6562.5   5400   8000
HR          4212.5   2350   4950
IT          5510.0   5000   6700

In [8]:
df.sort_values(by="Salary", ascending=False)

       Name Department  Salary  Bonus  Total
9      Judy    Finance    7200    800   8000
18    Sybil    Finance    7100    750   7850
21   Victor    Finance    6900    700   7600
12  Mallory    Finance    6700    650   7350
24   Yvonne    Finance    6500    650   7150
6     Grace    Finance    6300    700   7000
2   Charlie         IT    6100    600   6700
25     Zara         IT    6000    550   6550
15    Peggy    Finance    6000    600   6600
3     Diana    Finance    5800    550   6350
16  Quentin         IT    5800    500   6300
22    Wendy         IT    5700    500   6200
13     Niaj         IT    5600    550   6150
7     Heidi         IT    5400    500   5900
19    Trent         IT    5300    450   5750
0     Alice         IT    5200    500   5700
10    Kevin         IT    5100    400   5500
4       Eve         IT    4900    450   5350
14   Olivia         HR    4600    350   4950
17   Rupert         HR    4400    300   4700
11    Laura         HR    4300    300   4600
5     Frank         HR    4200    350   4550
23   Xavier         HR    4200    300   4500
1       Bob         HR    4100    300   4400
20      Uma         HR    4000    200   4200
8      Ivan         HR    3900    250   4150

In [9]:
df.nlargest(5, "Salary")

       Name Department  Salary  Bonus  Total
9      Judy    Finance    7200    800   8000
18    Sybil    Finance    7100    750   7850
21   Victor    Finance    6900    700   7600
12  Mallory    Finance    6700    650   7350
24   Yvonne    Finance    6500    650   7150

In [10]:
def tax(salary):
    return salary * 0.1

df["Tax"] = df["Salary"].apply(tax)
df.head()

      Name Department  Salary  Bonus  Total    Tax
0    Alice         IT    5200    500   5700  520.0
1      Bob         HR    4100    300   4400  410.0
2  Charlie         IT    6100    600   6700  610.0
3    Diana    Finance    5800    550   6350  580.0
4      Eve         IT    4900    450   5350  490.0

In [11]:
df.to_csv("output.csv", index=False)